python3 "CellTranspose.py" \
    --num-workers 2 \
    --epochs 500 \
    --n-chan 2 \
    --batch-size 8 \
    --eval-batch-size 48 \
    --dataset-name "Cellpose" \
    --results-dir "/mnt/12F9CADD61CB0337/syGlass/inquiry_test/cp_data_results/" \
    --train-dataset "/mnt/5400C9CC66E778B9/Ram/work/cell_analysis/datasets/datasets/generalist_cellpose/Generalized/train" \
    --val-dataset "/mnt/5400C9CC66E778B9/Ram/work/cell_analysis/datasets/datasets/generalist_cellpose/Generalized/test" \
    --test-dataset "/mnt/5400C9CC66E778B9/Ram/work/cell_analysis/datasets/datasets/generalist_cellpose/Generalized/test" \
    --calculate-ap
